front:
  container_name: "front"
  environment:
    TZ: "America/Argentina/Buenos_Aires"
    NODE_ENV: "production"
    REACT_APP_API: "http://192.168.1.2:3001/"
    REACT_APP_CDN_URL: "http://192.168.1.2:3002/"
  build: ./front
  working_dir: /app
  ports:
    - "80:3000"
  command: '/app/entrypoint.sh'
api:
  container_name: "api"
  links:
    - db
  environment:
    TZ: "America/Argentina/Buenos_Aires"
    NODE_ENV: "production"
  build: ./api
  working_dir: /app
  ports:
    - "3001:3001"
  command: '/app/entrypoint.sh'
db:
  container_name: "db"
  image: mongo:3.4.0
  environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
  volumes:
    - ../catalogue-static/data/db:/data/db
  ports:
      - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null 
static:
  container_name: "static"
  environment:
    TZ: "America/Argentina/Buenos_Aires"
    NODE_ENV: "production"
  build: ./static
  working_dir: /app
  ports:
    - "3002:3002"
  volumes:
    - ~/.catalogue/files/:/var/www/catalogue_static/data:ro
  command: '/app/entrypoint.sh'
