version: '3'
services:
  traefik:
    container_name: "traefik"
    image: traefik:1.5.2-alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/elballetdelosimbeciles/ctl/prd/traefik.toml:/traefik.toml:ro
  front_prd:
    container_name: "front_prd"
    environment:
      TZ: "America/Argentina/Buenos_Aires"
      NODE_ENV: "production"
      NPM_CONFIG_PREFIX: "/home/node/.npm-global"
    build: ./front
    labels:
      traefik.backend: "front"
      traefik.frontend.rule: "Host:catalogue.cf,www.catalogue.cf,"
      traefik.enable: "true"
      traefik.port: "3000"
  api_prd:
    container_name: "api_prd"
    environment:
      TZ: "America/Argentina/Buenos_Aires"
      NODE_ENV: "production"
      DB_HOST: "db_prd"
      ORIGIN: "https://catalogue.cf,https://www.catalogue.cf"
    build: ./api
    labels:
      traefik.backend: "api"
      traefik.frontend.rule: "Host:api.catalogue.cf"
      traefik.enable: "true"
      traefik.port: "3001"
  db_prd:
    container_name: "db_prd"
    image: mongo:3.4.0
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles --logpath=/dev/null 
  static_prd:
    container_name: "static_prd"
    image: nginx:1.13.8-alpine
    volumes:
      - /home/elballetdelosimbeciles/.catalogue/files/:/usr/share/nginx/html:ro
    labels:
      traefik.backend: "static"
      traefik.frontend.rule: "Host:static.catalogue.cf"
      traefik.enable: "true"
      traefik.port: "80"
networks:
  default:
