front_prd:
  container_name: "front_prd"
  environment:
    TZ: "America/Argentina/Buenos_Aires"
    NODE_ENV: "production"
    REACT_APP_API: "http://13.27.3.239:3001/"
    REACT_APP_CDN_URL: "http://13.27.3.239:3002/"
  build: ./front
  working_dir: /app
  ports:
    - "80:3000"
  command: '/app/entrypoint.sh'
api_prd:
  container_name: "api_prd"
  links:
    - db_prd
  environment:
    TZ: "America/Argentina/Buenos_Aires"
    NODE_ENV: "production"
    DB_HOST: "db_prd"
    ORIGIN: "*"
  build: ./api
  working_dir: /app
  ports:
    - "3001:3001"
  command: '/app/entrypoint.sh'
db_prd:
  container_name: "db_prd"
  image: mongo:3.4.0
  environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
  ports:
      - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null 
static_prd:
  container_name: "static_prd"
  environment:
    TZ: "America/Argentina/Buenos_Aires"
    NODE_ENV: "production"
  build: ./static
  working_dir: /app
  ports:
    - "3002:3002"
  volumes:
    - ~/.catalogue/files/:/app/data:ro
  command: '/app/entrypoint.sh'
