logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

# WEB interface of Traefik
[web]
address = ":3000"

# REST API interface of Traefik
[api]
address = ":3001"

# STATIC FILES SERVER (jpeg, mp3) interface of Traefik
[static]
address = ":3002"

# Connection to docker host system (docker.sock)
[docker]
domain = "catalogue.cf"
watch = true
# This will hide all docker containers that don't have explicitly  
# set label to "enable"
exposedbydefault = false

# Force HTTPS
#[entryPoints]
#  [entryPoints.http]
#  address = ":80"
#    [entryPoints.http.redirect]
#    entryPoint = "https"
#  [entryPoints.https]
#  address = ":443"
#    [entryPoints.https.tls]
  
# Let's encrypt configuration
#[acme]
#  email="email@mycoolapp.com"
#  storage="/etc/traefik/acme.json"
#  entryPoint="https"
#  acmeLogging=true
#  onDemand=true
#  OnHostRule=true